#!/usr/bin/env python3
"""Write tests/card_golden.h: golden values from the crisplab model for tests/test_image.c.

The model renders the shipped masters (res/cards/<R><S>.png) through the shipped pipeline (candidate
'art+darkbias+sharpen+clamp' in candidates/shipped.json: clean_master, the card resampler,
card_finish) for a few cards and heights. Per sprite the header keeps the per-channel sums and 64
sampled pixels: the 24 that the resampler changes most against the plain box, the 24 on the
strongest edges among the rest, and 16 random ones, all inside the frame ring. The C sprites must match the samples within 1 LSB
and the sums within npix/16 (proto/check.py compares whole sprites).

usage: make_golden.py [out.h]      (default tests/card_golden.h; re-run after changing the masters)
"""
import json
import random
import sys
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import crisplab as cl  # noqa: E402

CARDS = ['AS', 'TC', 'QH', 'KS']
HEIGHTS = [72, 96, 128, 160, 257]
N_CHANGE, N_EDGE, N_RANDOM = 24, 24, 16


def model(ship, h, cand):
    cw, ch = cl.card_size(h)
    return cl.card_finish(cl.resample(cl.clean_master(ship), cw, ch, cl.resolve(cand, ch)))


def samples(new, box, seed):
    H, W = new.shape[:2]
    inner = np.zeros((H, W), bool)       # the art, not the frame ring and corners (finish is shared)
    inner[2:H - 2, 2:W - 2] = True
    change = np.where(inner, np.abs(new - box).sum(axis=2), -1).ravel()
    Y = cl.luma(new[..., :3].astype(float))
    rng_ = np.where(inner, cl._minmax_filter(Y, 3, np.maximum) - cl._minmax_filter(Y, 3, np.minimum), -1).ravel()
    inner = inner.ravel()
    picked = []
    for i in np.argsort(-change, kind='stable')[:N_CHANGE]:
        picked.append(int(i))
    taken = set(picked)
    for i in np.argsort(-rng_, kind='stable'):
        if len(picked) == N_CHANGE + N_EDGE:
            break
        if int(i) not in taken:
            picked.append(int(i))
            taken.add(int(i))
    r = random.Random(seed)
    while len(picked) < N_CHANGE + N_EDGE + N_RANDOM:
        i = r.randrange(H * W)
        if inner[i] and i not in taken:
            picked.append(i)
            taken.add(i)
    return sorted((i % W, i // W) for i in picked)


def main(argv):
    out = Path(argv[1]) if len(argv) > 1 else cl.REPO / 'tests' / 'card_golden.h'
    cands = {c['name']: c for c in json.loads((HERE.parent / 'candidates' / 'shipped.json').read_text())}
    shipped, box = cands['art+darkbias+sharpen+clamp'], {'name': 'current'}
    lines = ['/* Generated by tools/crisplab/proto/make_golden.py from the crisplab model (candidate',
             ' * \'art+darkbias+sharpen+clamp\', the shipped card resampler) and res/cards/<card>.png. Do not edit;',
             ' * re-run it after changing the masters or the resampler. Sprites are premultiplied 0xAARRGGBB. */',
             '#ifndef FC_CARD_GOLDEN_H', '#define FC_CARD_GOLDEN_H', '', '#include <stdint.h>', '',
             'typedef struct CardGoldenSample { uint16_t x, y; uint32_t argb; } CardGoldenSample;', '',
             'typedef struct CardGolden {',
             '    const char      *card;      /* <rank><suit>, res/cards/<card>.png */',
             '    int              cw, ch;',
             '    long             sum[4];    /* B, G, R, A summed over the sprite */',
             '    CardGoldenSample s[%d];' % (N_CHANGE + N_EDGE + N_RANDOM),
             '} CardGolden;', '', 'static const CardGolden card_golden[] = {']
    for c in CARDS:
        ship = np.asarray(Image.open(cl.REPO / 'res' / 'cards' / (c + '.png')).convert('RGBA'))
        for h in HEIGHTS:
            cw, ch = cl.card_size(h)
            new = model(ship, h, shipped)
            old = model(ship, h, box)
            argb = (new[..., 3] << 24) | (new[..., 0] << 16) | (new[..., 1] << 8) | new[..., 2]
            sums = [int(new[..., k].sum()) for k in (2, 1, 0, 3)]
            pts = samples(new, old, '%s%d' % (c, h))
            lines.append('    { "%s", %d, %d, { %dL, %dL, %dL, %dL }, {' % ((c, cw, ch) + tuple(sums)))
            row = []
            for k, (x, y) in enumerate(pts):
                row.append('{ %d, %d, 0x%08xu }' % (x, y, int(argb[y, x])))
                if len(row) == 4 or k == len(pts) - 1:
                    lines.append('        ' + ', '.join(row) + ',')
                    row = []
            lines.append('    } },')
    lines += ['};', '', '#endif', '']
    out.write_text('\n'.join(lines))
    print(out)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
