/*
 * Solitaire HD — which XP deals can be won (the "winnable deals only" extra), precomputed.
 *
 * XP deals by seed = time(NULL) & 0x7FFF (game.h sol_deal_board), so there are 32768 deals. Each was
 * solved offline by the full-information solver (solver.h) for the four rule cases, and every solution
 * was replayed through the session (sol_press / sol_begin_drag / sol_drop) to a win:
 *
 *   case                     draw   passes                 used for scoring
 *   SOL_SEEDS_DRAW1          one    unlimited              Standard, None
 *   SOL_SEEDS_DRAW3          three  unlimited              Standard, None
 *   SOL_SEEDS_DRAW1_VEGAS    one    1 (no recycle)         Vegas
 *   SOL_SEEDS_DRAW3_VEGAS    three  3 (2 recycles)         Vegas
 *
 * A deal is WINNABLE (a solution was found and replayed), UNSOLVABLE (the search proved that no
 * sequence of moves wins) or UNKNOWN (the node budget ran out first). Only WINNABLE deals are offered:
 * UNKNOWN counts as not winnable. The table shipped now was generated before the solver checked the
 * move filters' proofs (solver.h): its UNSOLVABLE entries are the filters' verdicts, a few of them
 * winnable after all (e.g. Draw Three seeds 11369 and 30665), so read them as "not found winnable";
 * WINNABLE is exact. `make seed-tables` brings the statuses up to date. The data (src/solitaire/winnable_seeds.c, 2 bits per seed, 32 KiB) is
 * generated by `make seed-tables` (tests/sol_seed_tables.c); sol_seed_table_info says how.
 */
#ifndef SOL_WINNABLE_SEEDS_H
#define SOL_WINNABLE_SEEDS_H

#include "game.h"

#include <stdint.h>

#define SOL_SEEDS 32768u

enum { SOL_SEEDS_DRAW1 = 0, SOL_SEEDS_DRAW3 = 1, SOL_SEEDS_DRAW1_VEGAS = 2, SOL_SEEDS_DRAW3_VEGAS = 3,
       SOL_SEEDS_CASES = 4 };
enum { SOL_SEED_UNKNOWN = 0, SOL_SEED_WINNABLE = 1, SOL_SEED_UNSOLVABLE = 2 };

/* Seed s of case c: bits ((s & 3) * 2) of byte s >> 2. */
extern const uint8_t  sol_seed_table[SOL_SEEDS_CASES][SOL_SEEDS / 4];
/* Deals per case and status: [case][SOL_SEED_*]. */
extern const uint32_t sol_seed_counts[SOL_SEEDS_CASES][3];
/* How the table was made (generator, budgets, weights), one line. */
extern const char     sol_seed_table_info[];

/* The case of a game: draw 1 or 3, scoring SOL_SCORING_* (Vegas = the pass-limited cases). */
static inline int sol_seeds_case(int draw, int scoring)
{
    int d3 = draw != 1;
    return scoring == SOL_SCORING_VEGAS ? (d3 ? SOL_SEEDS_DRAW3_VEGAS : SOL_SEEDS_DRAW1_VEGAS)
                                        : (d3 ? SOL_SEEDS_DRAW3 : SOL_SEEDS_DRAW1);
}

static inline int sol_seed_status(int scase, unsigned seed)
{
    if (scase < 0 || scase >= SOL_SEEDS_CASES) return SOL_SEED_UNKNOWN;
    seed &= SOL_SEEDS - 1;
    return (sol_seed_table[scase][seed >> 2] >> ((seed & 3) * 2)) & 3;
}

/* The first seed at or after seed & 0x7FFF (wrapping round at 32768) whose deal is WINNABLE in case
 * scase; seed & 0x7FFF itself if no deal is (an empty table). */
static inline unsigned sol_seed_next_winnable(int scase, unsigned seed)
{
    seed &= SOL_SEEDS - 1;
    for (unsigned i = 0; i < SOL_SEEDS; i++) {
        unsigned s = (seed + i) & (SOL_SEEDS - 1);
        if (sol_seed_status(scase, s) == SOL_SEED_WINNABLE) return s;
    }
    return seed;
}

#endif
